kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-nodes
data:
  prometheus.yml: |
    global: 
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting: 
      alertmanagers:
      - static_configs: 
        - targets: 
    rule_files:
    scrape_configs:
      - job_name: 'rhel_gui'
        static_configs:
        - targets: ['192.168.99.106:9100']
      - job_name: 'rhel_cli'
        static_configs:
        - targets: ['192.168.99.102:9100']